"""add_epub_support_fields

Revision ID: 01437ac187e7
Revises: f3ec1be8d70c
Create Date: 2026-02-05 17:58:06.468863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01437ac187e7'
down_revision: Union[str, None] = 'f3ec1be8d70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_type', sa.String(length=20), nullable=False, server_default='txt'))
    op.add_column('books', sa.Column('epub_structure', sa.Text(), nullable=True))
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'epub_structure')
    op.drop_column('books', 'book_type')
    # ### end Alembic commands ###

